# Basics of financial math

## 1. Rate of return
Given a time series $p = \{p_0, p_1, ...\}$, the single-period rate of return at time $t$ is
$$ r = \frac{p_t-p_0}{p_0} = \frac{p_t}{p_0} - 1 $$

If we buy a stock at \$100, 6 months later it grows to \$102 and a year later to \$104, the total, or cumulative return is
$$ r = \frac{104}{100} - 1 = 0.04$$
Alternatively, we can compound semi-anually, assuming a return of $r_1$ in the first half and $r_2$ in the second half:
$$ 1 + r = (1+r_1)(1+r_2) = \frac{102}{100} \frac{104}{102} = 1.04$$
Or quarterly returns:
$$ 1 + r = (1+r_1)(1+r_2)(1+r_3)(1+r_4)$$

Suppose that we have two strategies, A and B. A returns 20% in 1 year, while B returns 6% for 3 months. To compare these strategies, we annualize B's returns:
$$ (1+0.06)^4 = 1+r_B $$
$$ r_B = 0.262 $$
So B has a higher compounding annual return.

In fact, the annualized return can be obtained as the geometric mean of the periodic returns:

$$ (1+r) = [(1+r_1)(1+r_2)...(1+r_n)]^{\frac{p}{n}} $$

where $r$ is the annualized return, $r_t$ is the return at period $t$, $n$ is the number of periods the investment was held for and p is the number of periods in a year. For quarterly returns, $p=4$, for yearly returns $p=1$.

## 2. Logarithm return
The $r_B$ calculated above is the effective annual intrest rate, as opposed to the nominal annual intrest rate: this is the periodic rate times the number of periods per year, in this case:
$$ r_{nominal} = 3*0.06 = 0.18 $$
This does not account for the intra-year compounding effect.
So we see that we can obtain the effective rate from the nominal rate as:
$$ 1+r = (1+\frac{r_{nominal}}{n})^n $$
In the limit of very large n (continuous compounding), for example a price changing every second, we get:
$$ 1+r = e^r_{nom} $$
So
$$ \frac{p_t}{p_0} = e^r_{nom} $$
$$ \Rightarrow r = \ln p_t - \ln p_0 $$

Note that 
$$ 1+r = (1+r_1) $$

In [1]:
import quandl
import numpy as np
quandl.ApiConfig.api_key = 'QQ4gF5jjG1U5ssS_h3-M'

aapl_table = quandl.get('WIKI/AAPL')

In [5]:
aapl = aapl_table.loc['2017-3', ['Open', 'Close']]
aapl['log_price'] = np.log(aapl.Close)
aapl['log_return'] = aapl.log_price.diff()
aapl

               Open   Close  log_price  log_return
Date
2017-03-01  137.890  139.79   4.940141         NaN
2017-03-02  140.000  138.96   4.934186   -0.005955
2017-03-03  138.780  139.78   4.940070    0.005884
2017-03-06  139.365  139.34   4.936917   -0.003153
2017-03-07  139.060  139.52   4.938208    0.001291
2017-03-08  138.950  139.00   4.934474   -0.003734
2017-03-09  138.740  138.68   4.932169   -0.002305
2017-03-10  139.250  139.14   4.935481    0.003311
2017-03-13  138.850  139.20   4.935912    0.000431
2017-03-14  139.300  138.99   4.934402   -0.001510
2017-03-15  139.410  140.46   4.944923    0.010521
2017-03-16  140.720  140.69   4.946559    0.001636
2017-03-17  141.000  139.99   4.941571   -0.004988
2017-03-20  140.400  141.46   4.952017    0.010446
2017-03-21  142.110  139.84   4.940499   -0.011518
2017-03-22  139.845  141.42   4.951734    0.011235
2017-03-23  141.260  140.92   4.948192   -0.003542
2017-03-24  141.500  140.64   4.946203   -0.001989
2017-03-27  139.390  140.88   4.947908    0.001705
2017-03-28  140.910  143.80   4.968423    0.020515
2017-03-29  143.680  144.12   4.970646    0.002223
2017-03-30  144.190  143.93   4.969327   -0.001319
2017-03-31  143.720  143.66   4.967449   -0.001878

As
$$ 1+r = ln\frac{p_t}{p_0} = ln\frac{p_t}{p_{t-1}} + ... + ln\frac{p_2}{p_1} + ln\frac{p_1}{p_0} $$
We can simply sum the daily returns to get the monthly return

In [6]:
month_return = aapl.log_return.sum()
print(month_return)

0.0273081001636184

## 3. Random Variables and Distributions